# version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8081:80"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
    depends_on:
      - database
    networks:
      - net_my_compose_milasibarani02

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - my-pg-volume-milasibarani02:/var/lib/postgresql/data
    networks:
      - net_my_compose_milasibarani02
    ports:
      - "5436:5432"

networks:
  net_my_compose_milasibarani02:
    driver: bridge

volumes:
  my-pg-volume-milasibarani02:
    name: my-pg-volume-milasibarani02

